version: '2.0'

services:
  node1.oneprovider:
    image: onedata/oneprovider:18.02.0-beta1
    hostname: node1.oneprovider.local
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistence"
        # data persistence
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        # Server SSL certificates
        #- "${OP_PRIV_KEY_PATH}:/etc/op_panel/certs/web_key.pem"
        #- "${OP_CERT_PATH}:/etc/op_panel/certs/web_cert.pem"
        #- "${OP_CHAIN_PATH}:/etc/op_panel/certs/web_chain.pem"
        # Additional, trusted CA certificates (any filename is accepted)
        #- "${OP_CACERTS_PATH}:/etc/op_panel/cacerts/customCaBundle.pem"
    ports:
      - "80:80"
      - "443:443"
      - "6665:6665"
      - "9443:9443"
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_LOG_LEVEL: "none" # prints logs to stdout (possible values: none, debug, info, error), by default set to info
      ONEPANEL_BATCH_MODE: "true"

      # If enabled, a new web cert will be generated with CN matching the
      #   ONEPANEL_GENERATED_CERT_DOMAIN and signed by OnedataTestWebServerCa
      # NOTE: The generation will be performed upon every startup, any
      #   existing certs will be backed up and placed in the same directory.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_GENERATE_TEST_WEB_CERT: "false"  # default: false
      # The generated test web cert will be issued for below domain.
      ONEPANEL_GENERATED_CERT_DOMAIN: "node1.oneprovider"  # default: ""
      # If enabled, onepanel will trust any server that has a cert signed by
      #   the OnedataTestWebServerCa.
      # WARNING: This functionality is devised for test purposes and must not
      #   be used in production.
      ONEPANEL_TRUST_TEST_CA: "false"  # default: false

      ONEPROVIDER_CONFIG: |
        cluster:
          domainName: "oneprovider.local"
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
          storages:
            NFS:
              type: "posix"
              mountPoint: "/volumes/storage"
        oneprovider:
          register: true
          name: "${PROVIDER_NAME}"
          subdomainDelegation: false
          domain: "${PROVIDER_FQDN}" # OR IP ADDRESS
          adminEmail: "getting-started@onedata.org"
          geoLatitude: ${GEO_LATITUDE}
          geoLongitude: ${GEO_LONGITUDE}
        onezone:
          domainName: "${ZONE_FQDN}" # OR IP ADDRESS
        onepanel:
          users:
            "admin":
              password: "password"
              userRole: "admin"
            "user":
              password: "password"
              userRole: "regular"
