version: '2.0'

services:
  node1.onezone:
    image: onedata/onezone:17.06.0-rc2
    hostname: node1.onezone.
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistance
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistence"
        # OpenId configuration
        #- "${AUTH_PATH}:/var/lib/oz_worker/auth.config"
        # DNS configuration
        #- "${DNS_PATH}:/var/lib/oz_worker/dns.config"
        # Onepanel
        #- "${OZ_PRIV_KEY_PATH}:/etc/oz_panel/certs/key.pem"
        #- "${OZ_CERT_PATH}:/etc/oz_panel/certs/cert.pem"
        #- "${OZ_CACERT_PATH}:/etc/oz_panel/cacerts/cacert.pem"
        #- "${OZ_CACERT_PATH}:/etc/oz_worker/cacerts/cacert.pem"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "7443:7443"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_LOG_LEVEL: "none" # prints logs to stdout (possible values: none, debug, info, error), by default set to info
      ONEZONE_CONFIG: |
        cluster:
          domainName: "onezone."
          autoDeploy: true
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
        onezone:
          name: "${ZONE_NAME}"
          domainName: "onezone"
        onepanel:
          users:
            "admin":
              password: "password"
              userRole: "admin"
            "user":
              password: "password"
              userRole: "regular"
