version: '2.0'

services:
  doc:
    image: docker.onedata.org/onedata-documentation:ID-dc96261773
    environment:
      ONEDATA_DOC_VERSION:
    volumes:
      - /usr/share/nginx/html

  nginx:
    restart: always
    image: nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - doc
    ports:
      - "8080:80"
