version: '2.0'

services:
  oneclient:
    image: onedata/oneclient:3.0.0-rc11
    privileged: true
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneclient-1
    environment:
      PROVIDER_HOSTNAME: $PROVIDER_HOSTNAME
      ONECLIENT_AUTHORIZATION_TOKEN: $ONECLIENT_AUTHORIZATION_TOKEN
      NO_CHECK_CERTIFICATE: 'true'
